FROM ubuntu

WORKDIR /root
RUN apt-get update
RUN apt-get install python3 python3-pip -y
RUN apt-get install apache2 -y
RUN apt-get install vim -y
COPY ./simpleC2/server.py server.py

EXPOSE 80
CMD ["apache2ctl", "-D", "FOREGROUND"]